- name: Async
  hosts: webservers
  gather_facts: no
  vars:
   packages:
    - nginx
  tasks:
   - name: Installation Block
     yum:
      name: "{{ packages }}"
      state: present
     async: 100
     poll: 0
     register: yum_state

   - name: debug
     debug:
      msg: "{{ yum_state }}"

   - name: Check Finished
     async_status:
      jid: "{{ yum_state.ansible_job_id }}" 
     register: job_result
     until: job_result.finished
     retries: 30

   - name: debug1
     debug:
      msg: "{{ yum_state }}"
   - name: debug1
     debug:
      msg: "{{ job_result }}"




